os: osx
osx_image: xcode12.2
language: swift
script: xcodebuild clean build test -project Clean\ Login/Clean\ Login.xcodeproj -scheme CI -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.0,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
